kosolabs/koso

frontend/src/lib/DagTable/row.svelte, frontend/src/lib/DagTable/state.ts
- **Simplify ghost logic now that rendering is simplified**
- **Remove complex logic**
=> tidy ghost logic

frontend/src/lib/DagTable/row.svelte, frontend/src/lib/DagTable/table.svelte
- **Allow nodes to programmatically change background**
- **Handle events better**
=> ui improvements

frontend/src/lib/DagTable/row.svelte, frontend/src/lib/DagTable/state.ts, frontend/src/lib/DagTable/table.svelte
- **Enable arrow keys to navigate the table**
- **working navigation, expand, collapse**
- **fix look of input box**
- **tidy row height changes**
- **Skip over collapsed nodes**
=> Keyboard controls: enable arrow key navigation, expand, and collapse

frontend/src/lib/DagTable/row.svelte, frontend/src/lib/DagTable/table.svelte
- **Try graph as a table**
- **snap**
- **Make it all work**
=> Convert flex box rows to a normal HTML table

backend/src/google.rs, backend/src/main.rs
- Introduce `verify_access` on `ws_handler` and `add_project_permission_handler`
- Rename `Claims` -> `User`
- Move `authenticate` to `google` module
=> Use verify_access to do authorization on all protected handlers

frontend/.prettierignore, frontend/components.json, frontend/eslint.config.js, frontend/package-lock.json, frontend/package.json, frontend/src/app.css, frontend/src/lib/DagTable/table.svelte, frontend/src/lib/components/ui/button/button.svelte, frontend/src/lib/components/ui/button/index.ts, frontend/src/lib/utils.ts, frontend/tailwind.config.js
- **Init shadcn and migrate one button**
- **Use teal color scheme**
=> Introduce shadcn-svelte and migrate a button

frontend/package-lock.json, frontend/package.json, frontend/src/lib/components/ui/alert-dialog/alert-dialog-action.svelte, frontend/src/lib/components/ui/alert-dialog/alert-dialog-cancel.svelte, frontend/src/lib/components/ui/alert-dialog/alert-dialog-content.svelte, frontend/src/lib/components/ui/alert-dialog/alert-dialog-description.svelte, frontend/src/lib/components/ui/alert-dialog/alert-dialog-footer.svelte, frontend/src/lib/components/ui/alert-dialog/alert-dialog-header.svelte, frontend/src/lib/components/ui/alert-dialog/alert-dialog-overlay.svelte, frontend/src/lib/components/ui/alert-dialog/alert-dialog-portal.svelte, frontend/src/lib/components/ui/alert-dialog/alert-dialog-title.svelte, frontend/src/lib/components/ui/alert-dialog/index.ts, frontend/src/lib/components/ui/popover/index.ts, frontend/src/lib/components/ui/popover/popover-content.svelte, frontend/src/lib/components/ui/sonner/index.ts, frontend/src/lib/components/ui/sonner/sonner.svelte, frontend/src/lib/project-share-modal.svelte, frontend/src/routes/+layout.svelte
- **Convert some bits**
- **init**
- **hack**
- **comp**
- **Make popover work**
- **Alternating row colors**
- **clean**
- **Tidy up alert**
- **Do some animations**
- **Use toast instead of alert**
- **Make confirmation dialog as scary as possible**
- **prettier**
=> Convert project sharing dialog to shadcn

frontend/src/lib/dag-table/row.svelte, frontend/src/lib/dag-table/table.svelte, frontend/src/lib/koso.test.ts, frontend/src/lib/koso.ts, frontend/src/routes/(auth)/projects/[projectId]/+page.svelte
- **Refactor Node object**
- **Refactor dragged**
- **Update tests**
- **Move highlighted**
- **fix bugs**
- **tidy**
- **Move expand/collapse to koso**
=> Refactor Node object so that more metadata can be associated

frontend/src/lib/dag-table/row.svelte, frontend/src/lib/dag-table/table.svelte, frontend/src/lib/koso.ts
Enable by opening the JS console and typing: `koso.debug.set(true)`
=> Enable debug UI behavior by: `koso.debug.set(true)`

frontend/src/lib/dag-table/row.svelte, frontend/src/lib/dag-table/table.svelte, frontend/src/lib/key-binding.ts, frontend/src/lib/koso.test.ts, frontend/src/lib/koso.ts
- **Move node around using arrows with option held down**
- **Prevent cycles from forming**
=> Feature to move nodes around with buttons / keyboard

frontend/package-lock.json, frontend/package.json, frontend/src/lib/dag-table/row.svelte, frontend/src/lib/dag-table/table.svelte, frontend/src/lib/koso.test.ts, frontend/src/lib/koso.ts, frontend/src/lib/stores.test.ts, frontend/src/lib/stores.ts, frontend/src/routes/(auth)/projects/[projectId]/+page.svelte
- **Use Immutable.js for Koso objects like Node**
- **convert expanded to a Immutable Set<Node>**
- **Fix svelte store not serializing updates**
- **Remove unnecessary functions**
- **No need to subscribe anymore**
=> Refactor Koso to use Immutable.js

frontend/src/app.html, frontend/src/lib/circular-progress-status.svelte, frontend/src/lib/circular-progress.svelte, frontend/src/lib/koso.ts, frontend/src/lib/responsive-text.svelte, frontend/src/lib/task-status-icon.svelte, frontend/src/lib/task-status-select.svelte
- **Make icons nice and consistent**
- **simplify stuff**
- **Hover over icon shows percentage**
=> Make status icons consistent with progress icons

frontend/src/app.css, frontend/src/lib/components/ui/chip/chip.svelte, frontend/src/lib/dag-table/row.svelte, frontend/src/routes/(auth)/projects/+page.svelte, frontend/src/routes/(auth)/projects/[projectId]/project-share-modal.svelte, frontend/tailwind.config.js
- **Simplify theme values**
- **Eliminate even-odd row classes**
- **Update color of child dropzone**
- **Round the drop target**
=> Simplify theme specs and update dropzone target colors

frontend/.prettierrc, frontend/eslint.config.js, frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/hooks.client.js, frontend/src/lib/api.ts, frontend/src/lib/nav.svelte.ts, frontend/svelte.config.js, frontend/tailwind.config.js
- **install**
- **Run prettier**
=> Install prettier jsdoc plugin and reformat project

backend/Cargo.lock, backend/Cargo.toml, backend/migrations/20241114235733_add_deleted_on_to_projects.down.sql, backend/migrations/20241114235733_add_deleted_on_to_projects.up.sql, backend/src/api/model.rs, backend/src/api/projects.rs, backend/src/tests.rs, frontend/src/lib/projects.ts, frontend/src/routes/(auth)/projects/+page.svelte, frontend/src/routes/+layout.svelte, frontend/src/routes/+page.svelte, frontend/tests/project-test.ts
- **Add delete endpoint to the backend**
- **Add delete functionality to the frontend**
=> Implement move project to trash

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/lib/components/ui/button/button.svelte, frontend/src/lib/components/ui/button/index.ts, frontend/src/lib/components/ui/toolbar-button/toolbar-button.svelte, frontend/src/lib/components/ui/tooltip/index.ts, frontend/src/lib/components/ui/tooltip/tooltip-arrow.svelte, frontend/src/lib/components/ui/tooltip/tooltip-content.svelte, frontend/src/lib/dag-table/drop-indicator.svelte
- **Migrate button to shadcn-svelte@next**
- **Migrate tooltip to shadcn-svelte@next**
- **Migrate toolbar-button to shadcn-svelte@next**
- **Migrate drop-indicator to shadcn-svelte@next**
=> Migrate Button and Tooltip to shadcn-svelte@next

backend/src/api/collab.rs, backend/src/api/collab/awareness.rs, backend/src/api/collab/client.rs, backend/src/api/collab/client_messages.rs, backend/src/api/collab/doc_updates.rs, backend/src/api/collab/msg_sync.rs, backend/src/api/collab/projects_state.rs, backend/src/api/google.rs, backend/src/api/model.rs, backend/src/tests.rs, frontend/src/lib/koso.svelte.ts, frontend/src/lib/koso.test.ts, frontend/src/lib/socket.ts
- **Implement client side awareness**
- **Implement backend**
- **Add user to awareness state and support multiple selection**
=> Implement Awareness in the backend

frontend/.prettierrc, frontend/src/lib/components/ui/alert/alert.svelte, frontend/src/lib/components/ui/button/button.svelte, frontend/src/lib/components/ui/toggle/toggle.svelte, frontend/src/lib/kosui/breadcrumbs/breadcrumbs.svelte, frontend/src/lib/kosui/button/button.svelte, frontend/src/lib/kosui/dialog/dialog.svelte, frontend/src/lib/kosui/link/link.svelte, koso.code-workspace
- **Adopt tailwind-variants more broadly in Kosui**
- **Prettier**
=> Adopt tailwind-variants in Kosui

frontend/src/lib/dag-table/table.svelte, frontend/tests/collab-test.ts, frontend/tests/dag-table-test.ts, frontend/tests/import-export-test.ts
Changed 'insert' label to 'add' on table and across all test files
=> Change 'insert' label to 'add'

frontend/src/lib/components/ui/toolbar-button/toolbar-button.svelte, frontend/src/lib/kosui/button/button.svelte, frontend/src/lib/kosui/tooltip/plain-tooltip.svelte, frontend/src/routes/storybook/tooltip/+page.svelte
- **Tooltip supports both fully controlled and render delegated**
- **Overload trigger to be either a snippet or a trigger reference**
=> controlled and delegated

backend/src/api/collab/notifications.rs, backend/src/api/yproxy.rs, frontend/src/lib/components/ui/task-action/task-action.svelte, frontend/src/lib/dag-table/koso.svelte.ts, frontend/src/lib/yproxy.ts
- **Add frontend logic for juggling**
- **Notify on juggle resolution**
- **Filter self-triggered notifications and use right name**
- **Fix blocked status**
=> Implement Juggler that reassigns tasks when they become actionable

frontend/src/lib/kosui/markdown/context.svelte.ts, frontend/src/lib/kosui/markdown/index.ts, frontend/src/lib/kosui/markdown/markdown-blockquote.svelte, frontend/src/lib/kosui/markdown/markdown-br.svelte, frontend/src/lib/kosui/markdown/markdown-code.svelte, frontend/src/lib/kosui/markdown/markdown-codespan.svelte, frontend/src/lib/kosui/markdown/markdown-def.svelte, frontend/src/lib/kosui/markdown/markdown-del.svelte, frontend/src/lib/kosui/markdown/markdown-em.svelte, frontend/src/lib/kosui/markdown/markdown-escape.svelte, frontend/src/lib/kosui/markdown/markdown-heading.svelte, frontend/src/lib/kosui/markdown/markdown-hr.svelte, frontend/src/lib/kosui/markdown/markdown-html.svelte, frontend/src/lib/kosui/markdown/markdown-image.svelte, frontend/src/lib/kosui/markdown/markdown-link.svelte, frontend/src/lib/kosui/markdown/markdown-list-item.svelte, frontend/src/lib/kosui/markdown/markdown-list.svelte, frontend/src/lib/kosui/markdown/markdown-paragraph.svelte, frontend/src/lib/kosui/markdown/markdown-space.svelte, frontend/src/lib/kosui/markdown/markdown-strong.svelte, frontend/src/lib/kosui/markdown/markdown-table.svelte, frontend/src/lib/kosui/markdown/markdown-text.svelte, frontend/src/lib/kosui/markdown/markdown-token.svelte, frontend/src/lib/kosui/markdown/markdown.svelte, frontend/src/routes/storybook/markdown/+page.svelte
- **Make Kosui markdown components stylable**
- **Make Kosui markdown components stylable**
=> stylable markdown

frontend/src/lib/components/ui/navbar/navbar.svelte, frontend/src/routes/(auth)/profile/+page.svelte, frontend/src/routes/(auth)/projects/[projectId]/+page.svelte, frontend/src/routes/(auth)/projects/[projectId]/dash/[taskId]/+page.svelte, frontend/src/routes/(auth)/projects/[projectId]/inbox/+page.svelte
Starting on the navbar visual indicators, still a WIP.
=> initial commit and prop declaration
